{% set version = '0.0.5' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-immundata
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/immundata_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/immundata/immundata_{{ version }}.tar.gz
  sha256: 16d814bea242b7bf2c3b3e71be1d29464ccd08a8d81a304b3b1ca31fc4bca53c

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-checkmate
    - r-cli
    - r-dbplyr
    - r-dplyr
    - r-duckplyr >=1.1.0
    - r-ggplot2
    - r-glue
    - r-jsonlite >=2.0.0
    - r-lifecycle
    - r-readr
    - r-rlang
    - r-tibble
  run:
    - r-base
    - r-r6
    - r-checkmate
    - r-cli
    - r-dbplyr
    - r-dplyr
    - r-duckplyr >=1.1.0
    - r-ggplot2
    - r-glue
    - r-jsonlite >=2.0.0
    - r-lifecycle
    - r-readr
    - r-rlang
    - r-tibble

test:
  commands:
    - $R -e "library('immundata')"           # [not win]
    - "\"%R%\" -e \"library('immundata')\""  # [win]

about:
  home: https://immunomind.github.io/docs/, https://github.com/immunomind/immundata
  license: Apache-2.0
  summary: Provides a unified data layer for single-cell, spatial and bulk T-cell and B-cell
    immune receptor repertoire data. Think AnnData or SeuratObject, but for AIRR data,
    a.k.a. Adaptive Immune Receptor Repertoire, VDJ-seq, RepSeq, or VDJ sequencing data.
  license_family: APACHE
  license_file:
    - LICENSE-2.0.txt

extra:
  recipe-maintainers:
    - conda-forge/r
